version: '3.8'

services:
  v2t:
    # The 'build' section tells Docker Compose to build an image.
    build:
      context: .
      dockerfile: Dockerfile.v2
    
    # The 'image' name will be used to tag the newly built image.
    # It uses the IMAGE_TAG environment variable, defaulting to 'latest' if not set.
    image: faceidcore/v2t:${IMAGE_TAG:-latest}
    
    # The container name also dynamically uses the tag for easier identification.
    container_name: faceidcore_v2t_${IMAGE_TAG:-latest}
    
    ports:
      - "10000:8000"  # HTTP
      - "10001:8001"  # gRPC
      - "10002:8002"  # Metrics
      
    # volumes:
    #   # This mounts your local model repository into the container.
    #   # It's great for development, as you can change your model files
    #   # without needing to rebuild the Docker image.
    #   - ./v2t:/models
      
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
