name: "diarizer"
backend: "python"
max_batch_size: 0

input [
  {
    name: "AUDIO_BYTES"
    data_type: TYPE_STRING
    dims: [ 1 ]
  },
  {
    name: "AUDIO_FORMAT"
    data_type: TYPE_STRING
    dims: [ 1 ]
    optional: true
  }
]

output [
  {
    name: "DIARIZATION_RTTM"
    data_type: TYPE_STRING
    dims: [ -1 ] 
  }
]

instance_group [
  {
    kind: KIND_GPU
  }
]

# Đã thêm tham số (giống như asr config)
parameters {
  key: "DEFAULT_AUDIO_FORMAT"
  value: { string_value: "wav" }
}